export const actionConstants = {
     ADD_LIST_ITEM : 'ADD_LIST_ITEM', 
     REMOVE_LIST_ITEM : 'REMOVE_LIST_ITEM',
     FETCH_LISTS_SUCCESS : 'FETCH_LISTS_SUCCESS', 
     FETCH_LISTS_ERROR : 'FETCH_LISTS_ERROR',
     DROP_TODO_ITEM : 'DROP_TODO_ITEM',
     ADD_TODO_ITEM : 'ADD_TODO_ITEM',
     REMOVE_TODO : 'REMOVE_TODO',
     UPDATE_TODO_DETAILS : 'UPDATE_TODO_DETAILS'
}